FROM dunglas/frankenphp:1-php8.5

WORKDIR /app

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN install-php-extensions pdo_mysql

COPY . /app/public

ENV SERVER_NAME=:80

EXPOSE 80